module.exports = {
  Ping: require('./ping'),
  Proverb: require('./proverb'),
  Roll: require('./roll'),
  Quirk: require('./quirk'),
  Name: require('./name'),
  Animal: require('./animal'),
  Country: require('./country'),
  //GoogleSearch: require('./googlesearch'),
  Help: require('./help'),
  Chargen: require('./character'),
  mtg: require('./mtgsearch'),
  g: require('./gamecommands'),
  pronouns: require('./pronouns'),
  pf: require('./pfsrd'),
};
